//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleInstaller {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleInstaller.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップにショートカットを作成する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string createDesktopShortcut {
            get {
                return ResourceManager.GetString("createDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータを削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string deleteSave {
            get {
                return ResourceManager.GetString("deleteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dirBtn {
            get {
                return ResourceManager.GetString("dirBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール済ファイルリストが正しくありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fileListIncorrect {
            get {
                return ResourceManager.GetString("fileListIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string installBtnText {
            get {
                return ResourceManager.GetString("installBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール先を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string installPath {
            get {
                return ResourceManager.GetString("installPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストールをキャンセルしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogInsCancel {
            get {
                return ResourceManager.GetString("LogInsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストールが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogInsComplete {
            get {
                return ResourceManager.GetString("LogInsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   をコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogInsCopy {
            get {
                return ResourceManager.GetString("LogInsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストールを開始しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogInsStart {
            get {
                return ResourceManager.GetString("LogInsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートが完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogUpdateComplete {
            get {
                return ResourceManager.GetString("LogUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   をコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogUpdateCopy {
            get {
                return ResourceManager.GetString("LogUpdateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートを開始しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogUpdateStart {
            get {
                return ResourceManager.GetString("LogUpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgDiscChangeFront {
            get {
                return ResourceManager.GetString("msgDiscChangeFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に交換して、ＯＫを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgDiscChangeRear {
            get {
                return ResourceManager.GetString("msgDiscChangeRear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストールをキャンセルしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInstallCancel {
            get {
                return ResourceManager.GetString("MsgInstallCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストールが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInstallComp {
            get {
                return ResourceManager.GetString("MsgInstallComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンインストール情報が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgUnfoundUninstallInfo {
            get {
                return ResourceManager.GetString("msgUnfoundUninstallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンインストールが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUninstallComp {
            get {
                return ResourceManager.GetString("MsgUninstallComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンイストールを実行してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUninstallConfirm {
            get {
                return ResourceManager.GetString("MsgUninstallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートをキャンセルしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUpdateCancel {
            get {
                return ResourceManager.GetString("MsgUpdateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUpdateComp {
            get {
                return ResourceManager.GetString("MsgUpdateComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %gametitle%がインストールされていません。\n%gametitle%を先にインストールして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUpdateNotinstalled {
            get {
                return ResourceManager.GetString("MsgUpdateNotinstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   をアンインストールする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string startMenuUninstall {
            get {
                return ResourceManager.GetString("startMenuUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール後にアプリを起動する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string titleInstall {
            get {
                return ResourceManager.GetString("titleInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンインストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string titleUninstall {
            get {
                return ResourceManager.GetString("titleUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string titleUpdate {
            get {
                return ResourceManager.GetString("titleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンインストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string uninstallBtn {
            get {
                return ResourceManager.GetString("uninstallBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンインストール先フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string uninstallPath {
            get {
                return ResourceManager.GetString("uninstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string updateBtnText {
            get {
                return ResourceManager.GetString("updateBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート先フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string updatePath {
            get {
                return ResourceManager.GetString("updatePath", resourceCulture);
            }
        }
    }
}
